name: Merge release to master
on:
  push:
    branches:
      - release
      - staging
jobs:
  start-log:
    runs-on: ubuntu-latest
    steps:
      - run: echo "foo bar"
      - run: echo "ref - ${{ github.ref }}"
      - run: echo "refname - ${{ github.refname }}"

  merge-granch:
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Backport release into master
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: release
          target_branch: master
          github_token: ${{ github.token }}
